# Generated by Django 4.2.5 on 2023-09-28 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='c_slug',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='slug',
            new_name='p_slug',
        ),
    ]
